name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.2.3
  - pytest=8.3.4
  - scipy=1.15.2
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
